# load output table generated by python script
output.table <- read.csv("R\\output_table.csv", header=TRUE)

# scale the descriptor data
output.scaled <- as.data.frame(scale(output.table))

# load user-created yield data (label reactions without yield data as NA)
yield.data <- read.csv("yields.csv", header=FALSE)

# append the yield data to the output table
output.scaled$yield <- yield.data

# remove rows where yield=NA
output.scaled <- output.scaled[!(is.na(output.scaled$yield)), ]

# Split into training and test set (70/30)
set.seed(1084)
size <- round(0.70*nrow(output.scaled))
training <- sample(nrow(output.scaled), size=size, replace=FALSE)
training.scaled <- output.scaled[training,]
test.scaled <- output.scaled[-training,]

# 10-fold cross-validation
train_control <- trainControl(method="cv", number=10, savePredictions=TRUE)

# random forest 
rfFit <- train(yield ~ ., data=training.scaled, trControl=train_control, method="rf", importance=TRUE)
png(filename="R\\plots\\rf70.png", width = 1000, height = 600)
predVals <- extractPrediction(list(rfFit70))
plotObsVsPred(predVals)
dev.off()
saveRDS(rfFit, "rds\\rfFit.rds")

# read in previously trained model (so you don't have to train it every time)
rfFit <- readRDS("rds\\rfFit.rds")