# install packages (if necessary) and load them
if (!require("pacman")) install.packages("pacman")
pacman::p_load(ggplot2, 
               caret,
               ModelMetrics,
               scales)

# set the working directory to the location of the rxnpredict folder
setwd("C:\\Users\\Derek\\Dropbox\\rxnpredict")


# ============================================================================
# Load descriptor and yield data and prepare data for modeling
# ============================================================================

# load output table generated by python script
output.table <- read.csv("R\\output_table.csv", header=TRUE)

# scale the descriptor data
output.scaled <- as.data.frame(scale(output.table))

# load user-created yield data (label reactions without yield data as NA)
yield.data <- as.numeric(unlist(read.csv("yields.csv", header=FALSE, stringsAsFactors=FALSE)))

# append the yield data to the output table
output.scaled$yield <- yield.data

# remove rows where yield=NA and columns containing at least one NA
output.scaled <- output.scaled[!(is.na(output.scaled$yield)), ]
output.scaled <- output.scaled[ , colSums(is.na(output.scaled)) == 0]


# ============================================================================
# Split data and train random forest model
# ============================================================================

# Split into training and test set (70/30)
set.seed(1084)
size <- round(0.70*nrow(output.scaled))
training <- sample(nrow(output.scaled), size=size, replace=FALSE)
training.scaled <- output.scaled[training, ]
test.scaled <- output.scaled[-training, ]

# 10-fold cross-validation
train_control <- trainControl(method="cv", number=10, savePredictions=TRUE)

# train the random forest model
set.seed(8915)
rfFit <- train(yield ~ ., data=training.scaled, trControl=train_control, method="rf", importance=TRUE)
saveRDS(rfFit, "rds\\rfFit.rds")

# uncomment to read in previously trained model (so you don't have to train it every time)
# rfFit <- readRDS("rds\\rfFit.rds")


# ============================================================================
# Calculate R^2 and RMSE using test set and generate calibration plot
# ============================================================================

# predict yields for test set
rf.pred <- predict(rfFit, test.scaled)

# calculate R^2 and RMSE and display in console
rf.r2 <- cor(rf.pred, test.scaled$yield)
rf.rmse <- rmse(rf.pred, test.scaled$yield)
paste0("R Squared = ", rf.r2, " and RMSE = ", rf.rmse)

# plot calibration plot (saves to R\user_plots\rf_calibration_plot.png)
df <- data.frame(x = rf.pred,
                 y = test.scaled$yield)
p1 <- ggplot(df, aes(x = x, y = y)) +
    geom_point(alpha = 0.4) + 
    scale_x_continuous(breaks = seq(0,100,25), lim=c(0, 100)) +
    labs(x='Predicted Yield', y='Observed Yield') +  
    geom_segment(aes(x=0,xend=100,y=0,yend=100), linetype="dashed") +
    geom_smooth(method="loess", se=FALSE)
ggsave(file="R\\user_plots\\rf_calibration_plot.png", width=5, height=4)


# ============================================================================
# Create variable importance plot
# ============================================================================

# read in variable importance from trained random forest model
rf_imp <- importance(rfFit$finalModel)
rf.imp.df <- cbind(as.data.frame(rf_imp), names(rf_imp[, 1]))
colnames(rf.imp.df)[1] <- "IncMSE"
colnames(rf.imp.df)[3] <- "descriptor"

# for descriptor names, replace "_" with " " and "." with "*"
rf.imp.df$descriptor <- gsub("_", " ", rf.imp.df$descriptor)
rf.imp.df$descriptor <- gsub("[.]", "*", rf.imp.df$descriptor)

# capitalize descriptor names
simpleCap <- function(x) {
    s <- strsplit(x, " ")[[1]]
    paste(toupper(substring(s, 1, 1)), substring(s, 2),
          sep="", collapse=" ")
}
rf.imp.df$descriptor <- sapply(rf.imp.df$descriptor, simpleCap)

# plot variable importance (saves to R\user_plots\rf_variable_importance.png)
# USER: change '10' on next line to modify minimum cutoff for IncMSE
p2 <- ggplot(rf.imp.df[rf.imp.df$IncMSE>10, ], aes(x=reorder(descriptor, IncMSE), y=IncMSE)) +
    geom_bar(stat="identity") +
    scale_y_continuous(labels = comma) +
    labs(x="", y="Increase in Mean Squared Error (%)") + 
    coord_flip()
ggsave(file="R\\user_plots\\rf_variable_importance.png", width=7, height=5)